---
swagger: "2.0"
# Info about this API specification.
info:
  description: "A Moodle Connector for Azure Logic Apps."
  version: "1.0.0"
  title: "Moodle Connector"
  contact:
    email: "enquiries@catalyst-au.net"
  license:
    name: "GPL 3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"

# Host information.
host: university.catalyst-au.net # This will need to be changed
basePath: /webservice/rest
schemes:
- https

# Api information.
paths:
  /server.php:
    post:
      summary: "a webservice"