---
swagger: "2.0"
# Info about this API specification.
info:
  description: "A Moodle Connector for Azure Logic Apps."
  version: "1.0.0"
  title: "Moodle Connector"
  contact:
    email: "enquiries@catalyst-au.net"
  license:
    name: "GPL 3.0"
    url: "https://www.gnu.org/licenses/gpl-3.0.en.html"

host: university.catalyst-au.net # This will need to be changed
basePath: /webservice/restful/server.php
schemes:
- https

# API information.
paths:
  /core_course_get_courses:
    post:
      summary: "Call Moodle webservices"
      description: "Use this conencto to communicate with Moodle via webservice functions."
      operationId: "core_course_get_courses"
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
      - name: Accept
        in: header
        required: true
        type: string
      - name: body
        in: body
        description: "The ids of the courses to return"
        required: false
        schema:
          type: object
          properties:
            options:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: integer
                    format: int32
                  description: ids
                  x-ms-summary: ids
              description: options
              x-ms-summary: options
      consumes:
      - application/json
      - application/xml
      - application/x-www-form-urlencoded
      produces:
      - application/json
      - application/xml
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"

securityDefinitions:
  api_key:
    type: apiKey
    in: header
    name: Authorization
